use_frameworks!

platform :ios, '8.0'

target 'Lcy001_Example' do
  pod 'Lcy001', :path => '../'

  target 'Lcy001_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
